### PR TITLE
Fix BoostFullAvailableTaps fails after 6 activations + fix typo

### PR DESCRIPTION
**Pull request by monkrel**
Fix for : 
https://github.com/shamhi/HamsterKombatBot/issues/26
https://github.com/shamhi/HamsterKombatBot/issues/33
https://github.com/shamhi/HamsterKombatBot/issues/35

BoostFullAvailableTaps boost struct:

```
{
            "id": "BoostFullAvailableTaps",
            "price": 0,
            "earnPerTap": 0,
            "maxTaps": 0,
            "maxLevel": 6,
            "cooldownSeconds": 39325,
            "level": 7,
            "maxTapsDelta": 0,
            "earnPerTapDelta": 0
}
```

### CODE REVIEW

**Comment by afdulfauzan** [comment]
image

**Comment by NkitN** [comment]
_```
2024-05-22 15:33:27 | ERROR    | 350 - андрей поляков  | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value
2024-05-22 15:33:30 | ERROR    | 350 - clips | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value
2024-05-22 15:33:30 | ERROR    | 350 - андрей поляков  | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value
2024-05-22 15:33:33 | ERROR    | 350 - clips | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value
2024-05-22 15:33:33 | ERROR    | 350 - андрей поляков  | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value
2024-05-22 15:33:36 | ERROR    | 350 - clips | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value
2024-05-22 15:33:36 | ERROR    | 350 - андрей поляков  | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value
```_

**Comment by NkitN** [comment]
`2024-05-22 15:33:27 | ERROR    | 350 - андрей поляков  | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value
2024-05-22 15:33:30 | ERROR    | 350 - clips | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value
2024-05-22 15:33:30 | ERROR    | 350 - андрей поляков  | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value
2024-05-22 15:33:33 | ERROR    | 350 - clips | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value
2024-05-22 15:33:33 | ERROR    | 350 - андрей поляков  | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value
2024-05-22 15:33:36 | ERROR    | 350 - clips | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value
2024-05-22 15:33:36 | ERROR    | 350 - андрей поляков  | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value`

**Comment by monkrel** [comment]
> `2024-05-22 15:33:27 | ERROR | 350 - андрей поляков | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value 2024-05-22 15:33:30 | ERROR | 350 - clips | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value 2024-05-22 15:33:30 | ERROR | 350 - андрей поляков | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value 2024-05-22 15:33:33 | ERROR | 350 - clips | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value 2024-05-22 15:33:33 | ERROR | 350 - андрей поляков | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value 2024-05-22 15:33:36 | ERROR | 350 - clips | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value 2024-05-22 15:33:36 | ERROR | 350 - андрей поляков | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value`

проблема не с моей частью кода

**Comment by NkitN** [comment]
> > `2024-05-22 15:33:27 | ERROR | 350 - андрей поляков | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value 2024-05-22 15:33:30 | ERROR | 350 - clips | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value 2024-05-22 15:33:30 | ERROR | 350 - андрей поляков | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value 2024-05-22 15:33:33 | ERROR | 350 - clips | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value 2024-05-22 15:33:33 | ERROR | 350 - андрей поляков | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value 2024-05-22 15:33:36 | ERROR | 350 - clips | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value 2024-05-22 15:33:36 | ERROR | 350 - андрей поляков | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value`
> 
> проблема не с моей частью кода

 а ты не знаешь что это за "не известная ошибка"

**Comment by NkitN** [comment]
`2024-05-22 15:31:07 | ERROR    | 194 - alexey | Unknown error while Tapping: 422, message='Unprocessable Entity', url=URL('https://api.hamsterkombat.io/clicker/tap')
2024-05-22 15:31:08 | ERROR    | 350 - clips | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value
2024-05-22 15:31:08 | ERROR    | 194 - никита колинин | Unknown error while Tapping: 422, message='Unprocessable Entity', url=URL('https://api.hamsterkombat.io/clicker/tap')
2024-05-22 15:31:08 | ERROR    | 350 - андрей поляков  | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value
2024-05-22 15:31:09 | ERROR    | 194 - dmitriy | Unknown error while Tapping: 422, message='Unprocessable Entity', url=URL('https://api.hamsterkombat.io/clicker/tap')
2024-05-22 15:31:11 | ERROR    | 350 - clips | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value
2024-05-22 15:31:11 | ERROR    | 350 - андрей поляков  | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value
2024-05-22 15:31:12 | ERROR    | 194 - никита колинин | Unknown error while Tapping: 422, message='Unprocessable Entity', url=URL('https://api.hamsterkombat.io/clicker/tap')
2024-05-22 15:31:13 | ERROR    | 194 - alexey | Unknown error while Tapping: 422, message='Unprocessable Entity', url=URL('https://api.hamsterkombat.io/clicker/tap')
2024-05-22 15:31:13 | ERROR    | 194 - dmitriy | Unknown error while Tapping: 422, message='Unprocessable Entity', url=URL('https://api.hamsterkombat.io/clicker/tap')
2024-05-22 15:31:14 | ERROR    | 350 - clips | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value
2024-05-22 15:31:14 | ERROR    | 350 - андрей поляков  | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value
2024-05-22 15:31:17 | ERROR    | 194 - никита колинин | Unknown error while Tapping: 422, message='Unprocessable Entity', url=URL('https://api.hamsterkombat.io/clicker/tap')
2024-05-22 15:31:17 | ERROR    | 194 - alexey | Unknown error while Tapping: 422, message='Unprocessable Entity', url=URL('https://api.hamsterkombat.io/clicker/tap')
2024-05-22 15:31:17 | ERROR    | 350 - clips | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value
2024-05-22 15:31:17 | ERROR    | 194 - dmitriy | Unknown error while Tapping: 422, message='Unprocessable Entity', url=URL('https://api.hamsterkombat.io/clicker/tap')
2024-05-22 15:31:17 | ERROR    | 350 - андрей поляков  | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value
2024-05-22 15:31:20 | ERROR    | 350 - clips | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value
2024-05-22 15:31:20 | ERROR    | 350 - андрей поляков  | Unknown error: cannot access local variable 'available_energy' where it is not associated with a value`
>еще такие ошибки есть

**Comment by nolikmq** [comment]
а куда этот фрагмент вставить?

**Pull request closed without merging**
